language: objective-c
before_install:
- gem install xcpretty
- gem install cocoapods
script:
- xcodebuild -project  -scheme 'BlobURLOfUIImageTests' -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES clean build test | xcpretty -c
